# -*- coding: utf-8 -*-
"""Python_assessment_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DUp_jNbcEoqJjBrzRYxhk0kIhyEPsKCS
"""

import numpy as np
import pandas as pd

#1
rgb_image=np.array([[[255,0,0],[0.255,0],[0,0,255]],
                    [[255,255,0],[255,0,255],[255,255,0]],
                    [[127,127,127],[200,200,200],[50,50,50]]])

def formula(r,g,b):
  m  = 0.2989*r + 0.5870*g +0.1140*b
  return b

#2
def normalise(h,w,a):

#3
data = np.array([[1,2,3],[4,5,6]])
da = np.reshape(data,-1)
da

#4
d = np.array([[1,2,3,4],[10,20,30,40],[60,70,80,90],[65,78,90,80]])
d

#5
g = np.array([[25,25,24,20],[20,20,20,-1],[19,20,21,-1]])
df= pd.DataFrame(g)

df.mean()

#6
def concat(a,b):
  c =np.concatenate(a,b)
  return c

a = np.array([[1,2],[43,44]])
b = np.array([4,5])
concat(a,b)

#7
data = {'Name':['Alice','Bob','Charlie','David','Eve','frank','grace'],
        'Age' : [25,30,35,40,45,50,55],
        'city':['New york','los angels','Chicago','Houstan','Phoenix','Miami','Boston'],
        'Department':['HR','IT','Finace','Marketing','Sales','IT','HR']}
df = pd.DataFrame(data)
df

df['Age'] = pd.to_numeric(df['Age'])
df['li'] = df[df['Age']< 45] & df[df['Department'] == 'HR']
df['li'] = df['Names','city']
df['li']

#8
data1 = {'Product':['Apple','Banana','Cherries','Dates','ElderBerries','Flour'],
         'category':['Fruit','Fruit','Fruit','Fruit','Fruit','Bakery'],
         'price':[1.20,0.50,3.00,2.50,4.00,1.50],
         'Promotion':[True,False,True,True,False,True]}
df1 = pd.DataFrame(data1)
df1

df1['a'] =  df1[df1['Product'] == 'Fruit'] & df1[df1['Promotion'] == False] & df1[df1['price'].mean()<df1['price']]
df1['a']

#9
a = {'Employee':['Alice','Bob','Charlie','David'],
     'Department':['HR','IT,','Finance','IT'],
    'Manager':['John','rachel','Emily','Rachel']}
b= {'Employee':['Alice','Charlie','Eve'],
    'project':['P1','P2','P1']}

x = pd.DataFrame(a)
y=pd.DataFrame(b)
c =pd.DataFrame
c = pd.concatenate(x,y,on = 'Employee',how = 'left')
c

# 10

data = {'Department':['Electronics','Electronics','Clothing','Clothing','Home Goods'],
        'salesperson':['alice','bob','charlie','david','eve'],
        'sales':[7000,5000,3000,4000,6000]}
df = pd.DataFrame(data)
df



