# -*- coding: utf-8 -*-
"""LVADSUSR128_vaishnavi_final_lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-jWI_XOuNA7IsXT6Yn5W7vctJVhJ67xL
"""

import pandas as pd
import numpy as np

df2 = pd.read_csv("/content/seeds.csv")
df2.head()

df2.info()

df2.isnull().sum()

df2.dropna(axis = 0,inplace =True)

#df2.fillna(df2.median(),axis=0,inplace=True)

df2.isnull().sum()

df2.head()

import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(data = df2.corr())

X = df2[['Area','Perimeter','Compactness','Length of kernel','Width of kernel','Length of kernel groove']]
y =df2['Asymmetry coefficient']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state= 0)

from sklearn.preprocessing import Normalizer
n =Normalizer()
df1 = n.fit_transform(x_train)

from sklearn.cluster import KMeans
inertia =[]
for i in range(1,11):
  kmeans = KMeans(n_clusters=i)
  kmeans.fit(df1)
  inertia.append(kmeans.inertia_)

plt.plot(range(1,11),inertia,marker='o')

import seaborn as sns
kmeans = KMeans(n_clusters=2)
kmeans.fit(df1)
sns.scatterplot(data = x_train,x='Area',y='Perimeter',hue=kmeans.labels_)
plt.plot()

