# -*- coding: utf-8 -*-
"""LVADSUSR128_vaishnavi_final_lab4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zwxuISt1OO6bLSN8yq39UOWGFkZpOI3l
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/social_network.csv")
df.head()

df.isnull().sum()

from sklearn.ensemble import IsolationForest
model = IsolationForest(n_estimators=100,contamination='auto',max_features=1.0)

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(7,5))
fig = sns.boxplot(data = df['suspicious_activity'])
plt.show()

model.fit(df[['suspicious_activity']])

df['anomaly']=model.predict(df[['suspicious_activity']])
df.head()

anomaly=df.loc[df['anomaly']==-1]
anomaly_index=list(anomaly.index)
print(anomaly)

accuracy = 100*list(df['anomaly']).count(-1)/(len(df['anomaly']))
accuracy

