# -*- coding: utf-8 -*-
"""LVADSUSR128_Vaishnavi_lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hv7eqCvsp754guq3wtNKH46cviXUQBHU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

df =pd.read_csv("/content/winequality-red.csv")
df.head()

df.info()

df.describe()

df.isnull().sum()

df = df.fillna(df.median())

df.isnull().sum()

df.head(5)

df['Quality_new'] = [0 if df['quality'][x]>=3 & df['quality'][x]<=6 else 1 for x in df['quality']]

X = df[['fixed acidity','volatile acidity','citric acid','residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH','sulphates','alcohol']]
y= df['Quality_new']

x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state =0)

from sklearn.preprocessing import Normalizer
n =Normalizer()
a = n.fit_transform(x_train)

knn = KNeighborsClassifier(n_neighbors =3)
knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)
accuracy = accuracy_score(y_pred,y_test)

accuracy

knn = KNeighborsClassifier(n_neighbors =10)
knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)
accuracy = accuracy_score(y_pred,y_test)
accuracy

