# -*- coding: utf-8 -*-
"""LVADSUSR128_Vaishnavi_FA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WsLceyurfrc0x0v2z3zOgQVQBH1MVVXR
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#1
df= pd.read_excel("/content/Walmart_Dataset Python_Final_Assessment.xlsx",index_col='Order ID')
df.head()

#2
df.info()
df.ffill()

#4
df.describe()

df['Sales'].mode()

df['Quantity'].mode()

df['Profit'].mode()

df['Profit'].median()

df['Quantity'].median()

df['Sales'].median()

#4
df1 = df.groupby('Category')['Sales'].sum().reset_index()
a =[]
b =[]
a =df1['Category']
b= df1['Sales']
plt.figure(figsize=(20,6))
plt.plot(a,b,marker ='o')
plt.xlabel("Category")
plt.ylabel("Sales")
plt.xticks(rotation = 45)
plt.title("Relation between category and sales")
plt.legend()
plt.show()

df2 = df.groupby('Category')['Profit'].sum().reset_index()
a =[]
b =[]
a =df2['Category']
b= df2['Profit']
plt.figure(figsize=(20,6))
plt.plot(a,b,marker ='o')
plt.xlabel("Category")
plt.ylabel("Profit")
plt.xticks(rotation = 45)
plt.title("Relation between category and profit")
plt.legend()
plt.show()

df3 = df.groupby('Category')['Quantity'].sum().reset_index()
a =[]
b =[]
a =df3['Category']
b= df3['Quantity']
plt.figure(figsize=(15,6))
plt.bar(a,b)
plt.xlabel("Category")
plt.ylabel("Quantity")
plt.xticks(rotation = 45)
plt.title("Relation between category and Quantity")
plt.legend()
plt.show()

df4 = df.groupby('Geography')['Sales','Profit'].sum().reset_index()
a =[]
b= []
c =[]
a = df4['Geography']
b =df4['Sales']
c =df4['Profit']
plt.figure(figsize=(50,6))
plt.plot(a,b,color='skyblue',label="Sales")
plt.plot(a,c,color ='r',label ='Profit')
plt.xlabel("City/Country")
plt.xticks(rotation =45)
plt.legend()
plt.show()

a =df['Order Date']
b= df['Ship Date']
plt.plot(a,b)
plt.figure(figsize=(50,6))
plt.xlabel('Order Date')
plt.ylabel("Ship Date")
plt.xticks(rotation = 45)
plt.show()

#5
df['Profit'].corr(df['Sales'])

df['Profit'].corr(df['Quantity'])

df['Sales'].corr(df['Quantity'])

"""#### The correlation between profit and quantity is high so the profit will increase when the quantity of product bought is increased"""

#6
plt.boxplot(df['Sales'])
plt.show()

plt.boxplot(df['Sales'],)
plt.show()

df

#7
df6 = df.groupby('Order Date')['Sales','Profit'].sum().reset_index()
a =[]
b= []
c =[]
a = df6['Order Date']
b =df6['Sales']
c =df6['Profit']
plt.figure(figsize=(40,6))
plt.bar(a,b,color='skyblue',label="Sales")
plt.bar(a,c,color ='r',label ='Profit')
plt.xlabel("Order Date")
plt.xticks(rotation =45)
plt.legend()
plt.show()

"""####There was a increase in sales during the jan of 2014 and the profit was also more combined.It can be also seen that there was fall in profit after the increase in sales.There were also months having very low sales and profit.Also it seen that there is fall of profit in some months of every year in the data"""

df7 = df.groupby('Category')['Sales'].sum().reset_index()
a = []
b= []
a = df7['Category']
b = df7['Sales']
plt.figure(figsize=(30,6))
plt.bar(a,b)
plt.xlabel("Category")
plt.ylabel("Sales")
plt.xticks(rotation =45)
plt.show()

#Customer Analysis
x = df.groupby('EmailID')['Sales'].count()
print(x)

df9 = df.groupby('EmailID')['Order Date'].max().reset_index()
df9
f = df9['EmailID']
g = df9['Order Date']
plt.scatter(f,g)
plt.show()

x = df.groupby('EmailID')['Sales'].max().reset_index()
a =[]
b =[]
a = x['EmailID']
b= x['Sales']
plt.plot(a,b)
plt.figure(figsize=(30,6))
plt.xlabel("EmailID")
plt.ylabel("Maximum sales by an Individual")
plt.xticks(rotation =90)
plt.show()

#Comprehensive Analysis

"""#####
* Through out the year from 2011 to 2015 it is seen that there is increase in sales of products and the sales is maximum at the year of 2015.
* The category which includes chair have more sales compared to others followed by mobile.The least category sold is fasteners.
* There was a increase in profit in jan month of 2014 compared to other months of sales data
* In three places the sales and profit was more compared to other places.While in other places the sales didn't have much variation
*Maximum quantity sold was 14 and the maximum profit attained was 6719.9808.
* There was only one high value customer who got more sales compared to other customers.
* The order date and ship date have linear relation which means the orders were delieverd properly.
"""

