# -*- coding: utf-8 -*-
"""LVADSUSR128_Vaishnavi_lab2ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17HQ0Ro3US_3PAumUVdndXWxCUum5Lq6c
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import LabelEncoder

df1 =pd.read_csv("/content/Mall_Customers.csv")
df1.head(5)

df1.describe()

df1.info()

df1.isnull().sum()

df1['Annual Income (k$)'] = df1['Annual Income (k$)'].fillna(df1['Annual Income (k$)'].median())

df1.isnull().sum()

encoder = LabelEncoder()
df1['Gender'] = encoder.fit_transform(df1['Gender'])
df1.head(5)

X = df1[['Age','Annual Income (k$)']]
y = df1['Spending Score (1-100)']

x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state =0)

n =Normalizer()
df1 = n.fit_transform(x_train)

from sklearn.cluster import KMeans
inertia =[]
for i in range(1,11):
  kmeans = KMeans(n_clusters=i)
  kmeans.fit(x_train)
  inertia.append(kmeans.inertia_)

plt.plot(range(1,11),inertia,marker='o')

import seaborn as sns
kmeans = KMeans(n_clusters=4)
kmeans.fit(df1)
sns.scatterplot(data = x_train,x='Age',y='Annual Income (k$)',hue=kmeans.labels_)
plt.plot()

