# -*- coding: utf-8 -*-
"""LVADAUSR128_vaishnavi_lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jRd_jXIGcBHUrfktnHmcWkn_dgn1VB1T
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/content/expenses.csv")
df.head()

df.info()

df.isnull().sum()

df.describe()

"""## Outliers"""

sns.boxplot(data=df['age'])
plt.show()

sns.boxplot(data=df['bmi'])
plt.show()

"""There are some outliers in the bmi columns and the datasets have no null values"""

df.drop_duplicates()

"""## LabelEncoding"""

l = LabelEncoder()
df['sex']=l.fit_transform(df['sex'])
df['smoker']=l.fit_transform(df['smoker'])
df['region']=l.fit_transform(df['region'])
df.head()

"""## Feature Description"""

df.drop(columns = ['sex','children'])

x = df[['age','bmi','smoker','region']]
y = df['charges']

"""## Train test split"""

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

"""## Model development"""

model=LinearRegression()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
m = mean_squared_error(y_pred,y_test)
print(m)

from sklearn.metrics import r2_score

rsquared = r2_score(y_pred,y_test)
rsquared

