# -*- coding: utf-8 -*-
"""LVADSUSR128_vaishnavi_final_lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ByWMvAhmm5vjFYGO1ZY3oRiMEphyGSgY
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,f1_score,recall_score
import numpy as np

df1 = pd.read_csv("/content/auto-mpg.csv")
df1.head()

df1.isnull().sum()

df1.info()

df1['displacement']=df1['displacement'].fillna(df1['displacement'].median())
df1['acceleration']=df1['acceleration'].fillna(df1['acceleration'].median())
df1['horsepower']=df1['horsepower'].ffill()

#df1.drop('car name',axis=1,inplace=True)

df1.isnull().sum()

import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(data = df1.corr())
plt.show()

df1.head(1)

X = df1[['cylinders','displacement','weight','acceleration','model year']]
y= df1['mpg']

x_train,x_test,y_train,y_test = train_test_split(X,y,test_size =0.3,random_state=0)

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
accuracy = accuracy_score(y_pred,y_test)
print(accuracy)
f1 = f1_score(y_pred,y_test)
print(f1)

