# -*- coding: utf-8 -*-
"""Python assessment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11PgYKjzdt2Djql7XgwjjnlQSebRf9ZJj
"""

#1

x = int(input("Enter the length : "))
y = int(input("Enter the width : "))
Area  = x * y
print("The area of rectangle is ",Area)

#2

h = int(input("enter the height : "))
w = int(input("enter the weight : "))
bmi = w/(h/100)**2
print(bmi)

#3
d = {"vais":"23","aish":"24","vishnu":"20"}
print(d)
a = input("Enter the name : ")
b = int(input("enter the score : "))
update_key = {a:b}
d[a] = b
print(d)

#4

a = int(input("enter the age : "))
if a < 18 :
  print("Minor")
elif a >= 18 and a < 60 :
  print("Adult")
else :
  print("senior")

# 5
for i in range (1,50):
  if i%2 == 0:
    print(i)

# 6

p = input("password : ")
while(p == "abc"):
    print("successful")
    break
else:
  input("Enter the password : ")

##7

def average(avr):
  n = input(int("enter no of numbers : "))
  for i in range (n):
    s = s + s[i]
  avr = s/n
  return avr

s= 0
l = []
n = int(input("enter no of numbers : "))
l.append(n)
for i in range (n):
    s =
avr = s/n

#8
vowels =['a','e','i','o','u']
p = input("enter a word")
for i in range (len(p)):
  if i in vowels:
    g = i.count()
else:
  print("run again")

# 9
import datetime
g =

# 10
try:
  a = 8
  b = i
  c= a+b
except ValueError:
    print("error")
finally:
  print("successful")

# 11
try:
  a = 0
except ValueError:
  print("correct value")
finally:
  print("successful")

# 12
def division(a,b):
  try:
    a= int(input("enter the numerator : "))
    b= int(input("enter the denominator : "))
    d = a/b
  except ZeroDivisionError:
    print("Enter value greater than 0")
  finally:
    print("successful")
  return d

division()

#13
def write(file_path,message):
  with open(file_path,"w") as file:
    content = file.write(message)
  return content

write("sample.txt","Hello,Python")

##14
with open("sample.txt","r") as file:
  r = file.read()
  print(r)

##15
with open("sample.txt","w") as file:
    content = file.writelines("abc")
print(content)

